version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      background:
        applies-to: version-updates
        patterns:
          - "*"
