name: Common setup
description: Common setup steps for jobs that use Nix
runs:
  using: composite
  steps:
    - name: Maximize build space
      if: runner.os == 'Linux'
      uses: AdityaGarg8/remove-unwanted-software@v2
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: Install nix
      uses: cachix/install-nix-action@v27
      with:
        install_url: https://releases.nixos.org/nix/nix-2.23.3/install

    - uses: cachix/cachix-action@v15
      with:
        name: holochain-binaries
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        extraPullNames: holochain-ci

    - name: Create deploy directory
      shell: bash
      run: mkdir -p deploy